version: "2.0"
services:
  server:
    image: meiduo_server:latest
    restart: always
    volumes:
      - /var/local/meiduo_mall/meiduo_server/logs:/var/log/
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "5"
    ports:
    - "8000:8000"


  web:
    image: meiduo_web:latest
    restart: always
    ports:
    - "8080:80"

#--------------第一次构建时请打开注释----------------

#  redis:
#    image: redis:6.0.13
#    restart: always
#    ports:
#      - "6379:6379"



