# Generated by Django 3.1.7 on 2021-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='spec',
            field=models.CharField(max_length=100, verbose_name='商品规格'),
        ),
    ]
