# Generated by Django 3.1.7 on 2021-07-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='邮箱'),
        ),
    ]
