# Generated by Django 3.1.7 on 2021-06-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210606_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodschannel',
            options={'ordering': ['group_id', 'sequence'], 'verbose_name': '商品频道', 'verbose_name_plural': '商品频道'},
        ),
    ]
