# Generated by Django 3.1.7 on 2021-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210606_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
